# coding:utf-8

# 图片有效期时间,秒
IMAGE_CODE_EXPIRES_SECONDS = 120

# 手机验证码有效期
SMS_CODE_EXPIRES_SECDONS = 3600

# 区域信息缓存有效期 秒
AREA_INFO_REDIS_EXPIRES_SECONDS = 86400
# redis缓存房屋信息的有效期
REDIS_HOUSE_INFO_EXPIRES_SECONDES = 86400

# 房屋列表一页数量
HOUSE_LIST_PAGE_CAPACITY = 3
# redis每次缓存房屋列表页数
HOUSE_LIST_REDIS_CACHED_PAGE = 2
# 房屋缓存时间
HOUSE_LIST_REDIS_EXPIRE_SECOND = 3600

#