# coding:utf-8

# 图片有效期时间,秒
IMAGE_CODE_EXPIRES_SECONDS = 120

# 手机验证码有效期
SMS_CODE_EXPIRES_SECDONS = 3600

# 区域信息缓存有效期 秒
AREA_INFO_REDIS_EXPIRES_SECONDS = 86400

# 房屋列表一页数量
HOUSE_LIST_PAGE_CAPACITY = 10